apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-secondary
  labels:
    app: redis
    role: secondary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: secondary
  template:
    metadata:
      labels:
        app: redis
        role: secondary
    spec:
      containers:
      - name: redis-secondary
        image: redis:latest
        ports:
        - name: redis-server
          containerPort: 6379
        command:
        - redis-server
        - "--slaveof"
        - "redis-primary"
        - "6379"