apiVersion: v1
kind: Service
metadata:
  name: redis-primary
  labels:
    app: redis
    role: primary
spec:
  ports:
  - port: 6379
    targetPort: redis-server
  selector:
    app: redis
    role: primary